import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://c9-communications.vercel.app';
  
  const routes = [
    '',
    '/about',
    '/blog',
    '/business',
    '/case-studies',
    '/challenges',
    '/contact',
    '/enterprise',
    '/greenfield',
    '/help',
    '/industries',
    '/industries/education',
    '/industries/healthcare',
    '/industries/hospitality',
    '/industries/non-profit',
    '/industries/professional-services',
    '/industries/real-estate',
    '/industries/retail',
    '/insights',
    '/managed',
    '/managed-it',
    '/managed-it/backup-disaster-recovery',
    '/managed-it/cloud-services',
    '/managed-it/helpdesk-support',
    '/managed-it/infrastructure',
    '/managed-it/network-solutions',
    '/managed-it/outsourcing',
    '/managed-it/security-solutions',
    '/managed-it/strategy-consulting',
    '/modern-workplace',
    '/pricing',
    '/privacy-policy',
    '/saas-experiment',
    '/site-map',
    '/solutions',
    '/solutions/cctv-people-count',
    '/solutions/collaboration',
    '/solutions/communication-tools',
    '/solutions/endpoint-management',
    '/solutions/productivity',
    '/startups',
    '/support',
    '/telco',
    '/telco/business-nbn',
    '/telco/c9voice',
    '/telco/contact-centre',
    '/telco/enterprise-ethernet',
    '/telco/fast-fibre',
    '/telco/inbound-services',
    '/telco/mobile-plans',
    '/telco/phone-system',
    '/telco/sip-trunking',
    '/telco/teams-calling',
    '/telco/voice-systems',
    '/telco-solutions',
    '/terms',
    '/why-c9',
    '/partners',
    '/careers',
    '/team',
    '/reviews',
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '' ? 'daily' : 'weekly',
    priority: route === '' ? 1.0 : route.split('/').length <= 2 ? 0.8 : 0.6,
  }));
}
