import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://c9-communications.vercel.app';
  
  const routes = [
    '',
    '/about',
    '/about/why-c9',
    '/about/team',
    '/about/careers',
    '/about/partners',
    '/about/reviews',
    '/business',
    '/case-studies',
    '/contact',
    '/enterprise',
    '/greenfield',
    '/industries',
    '/industries/education',
    '/industries/healthcare',
    '/industries/hospitality',
    '/industries/non-profit',
    '/industries/professional-services',
    '/industries/real-estate',
    '/industries/retail',
    '/managed-it',
    'https://c9defense.com.au/',
    '/managed-it/cloud-services',
    '/managed-it/helpdesk-support',
    '/managed-it/infrastructure',
    '/managed-it/network-solutions',
    '/managed-it/outsourcing',
    'https://c9defense.com.au/',
    '/managed-it/strategy-consulting',
    '/modern-workplace',
    '/modern-workplace/productivity',
    '/modern-workplace/communication-tools',
    '/modern-workplace/endpoint-management',
    '/modern-workplace/collaboration',
    '/modern-workplace/secure-remote-work',
    '/modern-workplace/cctv-people-count',
    '/modern-workplace/managed-print',
    '/modern-workplace/visitor-solution',
    '/modern-workplace/compliance-data-protection',
    '/pricing',
    '/privacy-policy',
    '/site-map',
    '/solutions',
    '/support',
    '/telco',
    '/telco/business-nbn',
    '/telco/c9voice',
    '/telco/contact-centre',
    '/telco/enterprise-ethernet',
    '/telco/fast-fibre',
    '/telco/inbound-services',
    '/telco/mobile-plans',
    '/telco/phone-system',
    '/telco/sip-trunking',
    '/telco/teams-calling',
    '/telco/voice-systems',
    '/terms',
    '/help/new-office-setup',
    '/help/fast-secure-internet',
    '/help/ad-on-hold',
    '/help/secure-wifi',
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '' ? 'daily' : 'weekly',
    priority: route === '' ? 1.0 : route.split('/').length <= 2 ? 0.8 : 0.6,
  }));
}
